# Generated by Django 2.0.5 on 2018-05-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manhours',
            name='mandays_lost',
            field=models.PositiveIntegerField(default=0, verbose_name='Man-Days Lost'),
        ),
        migrations.AlterField(
            model_name='manhours',
            name='manhours_worked_contract',
            field=models.PositiveIntegerField(default=0, verbose_name='Manhours Worked Contract'),
        ),
        migrations.AlterField(
            model_name='manhours',
            name='manhours_worked_regular',
            field=models.PositiveIntegerField(default=0, verbose_name='Manhours Worked Regular'),
        ),
    ]
