# Generated by Django 2.0.5 on 2018-05-31 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputforms', '0002_auto_20180530_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allaccident',
            name='age',
            field=models.PositiveSmallIntegerField(default='21', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)], verbose_name='Age'),
        ),
    ]
